version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: abc
      WORDPRESS_DB_PASSWORD: 123456abc
      WORDPRESS_DB_NAME: abc
   # volumes:
      - wordpress:/var/www/html

  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: abc
      MARIADB_USER: abc
      MARIADB_PASSWORD: 12356abc
      MARIADB_ROOT_PASSWORD: 123456abc
    # volumes:
      - db:/var/lib/mysql
